apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
        - name: app-a
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
