apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: i4-v1
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: main
    directory:
      jsonnet:
        tlas:
          - {}
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
