apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-official-i4
  namespace: argocd
spec:
  project: default
  source:
    path: apps
    repoURL: https://github.com/fcchn4/argocd-demo.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
